<?xml version="1.0"?>
<!DOCTYPE ee[
        <!ELEMENT classrooms (classroom)>
        <!ELEMENT classroom (#PCDATA)>
        ]>
<classrooms>
    <classroom>AL</classroom>
    <classroom>IABD</classroom>
    <classroom>MOC</classroom>
    <classroom>IBC</classroom>
</classrooms>
